//! Regenerates and verifies `reference.json`, the hex-exact cross-SDK
//! test vectors for `pith-audio`.
//!
//! Every vector is computed through the crate's public API from inputs
//! that are either the committed conformance fixture
//! (`tests/fixtures/tone.wav`) or synthetic streams built byte-by-byte
//! here from [`pith_audio::reference`]'s SplitMix64 synthesis — no RNG
//! beyond the fixed SplitMix64 stream, no time, no transcendentals, no
//! platform-dependent bytes — so the output is byte-stable everywhere.
//!
//! Numeric policy: this crate's vectors record only *discrete* values
//! (integer PCM samples, peak `(t, f)` sets, fingerprints, hashes).
//! No raw `f64` spectrum bins are committed, so no per-vector float
//! tolerance policy is needed; the byte contract is exact everywhere.
//! The spectral peak decisions are separated by orders of magnitude
//! from the ulp-level trig drift any platform's `sin`/`cos` may show,
//! which the committed burst-shaped corpora guarantee by construction.
//!
//! Usage:
//! - `gen-reference gen` — recompute every vector and write
//!   `reference.json` at the repository root.
//! - `gen-reference verify` — recompute and compare byte-for-byte
//!   against the committed copy; exit 1 on drift. This is the CI gate.

mod builder;

use std::fs;
use std::path::PathBuf;
use std::process::ExitCode;

use pith_audio::reference::{mono_average, voices_samples, voices_samples_stereo};
use pith_audio::wav;
use pith_audio::{Match, Signature, build_index, match_signature, signature, signature_of_wav};
use pith_digest::{fnv1a64, sha256};

use builder::{chunk, fmt_chunk, pcm_wav, pcm16_data, wav_file};

/// Where the committed copy lives, relative to the repository root.
const REFERENCE_PATH: &str = "reference.json";
/// The decode/signature conformance fixture, relative to the repository root.
const FIXTURE_PATH: &str = "tests/fixtures/tone.wav";

/// Seeds of the synthetic corpora. All five corpora are generated by
/// [`builder::voices_samples`] from these seeds; the values themselves
/// are pinned in `reference.json`, so a seed change fails `verify`
/// loudly instead of drifting silently.
const SEED_MONO: u64 = 0xC0_FFEE;
const SEED_CONTENT: u64 = 0xD1_CE;
const SEED_PREFIX: u64 = 0xBE_EF;
const SEED_FILLER: u64 = 0xE5_A5;
const SEED_OTHER: u64 = 0xF0_0D;
const SEED_STEREO_L: u64 = 0x11;
const SEED_STEREO_R: u64 = 0x22;

/// One decoded WAV measurement: the fields reference.json records for
/// every decode vector.
struct Decoded {
    sample_rate: u32,
    channels: u16,
    bits_per_sample: u16,
    frames: usize,
    decoded_samples: usize,
    /// The decoded canonical samples, when the vector pins them.
    samples: Vec<i32>,
    pcm_i32_le_sha256: String,
    pcm_i32_le_fnv1a64: String,
}

/// One extracted signature measurement.
struct Signed {
    frames: u32,
    peak_count: usize,
    /// `(t, f)` pairs in signature order.
    peaks: Vec<(u32, u16)>,
    fingerprint: u64,
}

/// Measures one WAV byte string through the public decode API.
fn measure(input: &[u8]) -> Decoded {
    let out = wav::decode(input).expect("vector input must decode");
    Decoded {
        sample_rate: out.sample_rate(),
        channels: out.channels(),
        bits_per_sample: out.bits_per_sample(),
        frames: out.frames(),
        decoded_samples: out.samples().len(),
        samples: out.samples().to_vec(),
        pcm_i32_le_sha256: hex(sha256(&pcm_le(out.samples()))
            .expect("sha256 of pcm")
            .as_bytes()),
        pcm_i32_le_fnv1a64: format!("{:016x}", fnv1a64(&pcm_le(out.samples()))),
    }
}

/// Measures interleaved PCM through the public signature API.
fn measure_signature(samples: &[i32], channels: u16) -> Signed {
    let sig = signature(samples, channels).expect("vector pcm must be accepted");
    signed(&sig)
}

/// Measures a WAV byte string through the `signature_of_wav` facade.
fn measure_signature_of_wav(input: &[u8]) -> Signed {
    let sig = signature_of_wav(input).expect("vector wav must be accepted");
    signed(&sig)
}

fn signed(sig: &Signature) -> Signed {
    Signed {
        frames: sig.frames(),
        peak_count: sig.len(),
        peaks: sig.peaks().iter().map(|p| (p.t, p.f)).collect(),
        fingerprint: sig.fingerprint(),
    }
}

/// Serializes peaks the way `peaks_sha256` hashes them: `u32`-LE `t`
/// then `u16`-LE `f`, one peak after another.
fn peaks_le(peaks: &[(u32, u16)]) -> Vec<u8> {
    let mut v = Vec::with_capacity(peaks.len() * 6);
    for &(t, f) in peaks {
        v.extend_from_slice(&t.to_le_bytes());
        v.extend_from_slice(&f.to_le_bytes());
    }
    v
}

fn pcm_le(samples: &[i32]) -> Vec<u8> {
    let mut v = Vec::with_capacity(samples.len() * 4);
    for &s in samples {
        v.extend_from_slice(&s.to_le_bytes());
    }
    v
}

fn hex(bytes: &[u8]) -> String {
    let mut s = String::with_capacity(bytes.len() * 2);
    for b in bytes {
        s.push_str(&format!("{b:02x}"));
    }
    s
}

/// The stable kind name a [`pith_digest::Error`] variant records as.
fn error_kind(e: &pith_digest::Error) -> &'static str {
    match e {
        pith_digest::Error::Truncated { .. } => "truncated",
        pith_digest::Error::InvalidMagic { .. } => "invalid-magic",
        pith_digest::Error::BadValue(_) => "bad-value",
        pith_digest::Error::Unsupported(_) => "unsupported",
        pith_digest::Error::TooLarge { .. } => "too-large",
    }
}

/// The stable kind name the facade's [`pith_audio::Error`] records as.
fn facade_error_kind(e: &pith_audio::Error) -> &'static str {
    match e {
        pith_audio::Error::BadValue(_) => "bad-value",
        pith_audio::Error::Unsupported(_) => "unsupported",
        pith_audio::Error::Decode(_) => "decode",
    }
}

// ------------------------------------------------------------------
// The vector inputs
// ------------------------------------------------------------------

/// 8-bit mono PCM centring: `0x00 -> -128`, `0x80 -> 0`, `0xFF -> 127`.
fn pcm8_offset_wav() -> Vec<u8> {
    pcm_wav(1, 1, 8_000, 8, &[0x00, 0x80, 0xFF, 0x01])
}

/// 24-bit sign extension, including the most negative sample
/// `00 00 80` and the positive max `FF FF 7F`.
fn pcm24_sign_extend_wav() -> Vec<u8> {
    pcm_wav(
        1,
        1,
        48_000,
        24,
        &[
            0x00, 0x00, 0x80, // -8388608
            0xFF, 0xFF, 0x7F, //  8388607
            0x00, 0x00, 0x00, //        0
            0xFF, 0xFF, 0xFF, //       -1
            0x00, 0x01, 0x00, //      256
        ],
    )
}

/// Float32 clamping endpoints and NaN mapping.
fn float32_clamp_wav() -> Vec<u8> {
    let mut data = Vec::new();
    for s in [0.0f32, -1.0, 1.0, 0.5, 1.5, f32::NAN] {
        data.extend_from_slice(&s.to_le_bytes());
    }
    pcm_wav(3, 1, 44_100, 32, &data)
}

/// Float64 exact halves and the pinned 1/3 rounding.
fn float64_thirds_wav() -> Vec<u8> {
    let mut data = Vec::new();
    for s in [0.25f64, -0.5, 1.0 / 3.0] {
        data.extend_from_slice(&s.to_le_bytes());
    }
    pcm_wav(3, 1, 44_100, 64, &data)
}

/// An odd-sized LIST chunk between `fmt ` and `data`: the pad byte
/// must be consumed for the walk to find `data`.
fn odd_chunk_pad_wav() -> Vec<u8> {
    wav_file(&[
        chunk(b"fmt ", &fmt_chunk(1, 1, 44_100, 16)),
        chunk(b"LIST", b"INFOX"),
        chunk(b"data", &[0x01, 0x00, 0xFE, 0xFF]),
    ])
}

/// A dangling byte after a whole 16-bit frame: dropped, never decoded.
fn partial_frame_wav() -> Vec<u8> {
    pcm_wav(1, 1, 8_000, 16, &[0x05, 0x00, 0xAA])
}

/// The mono signature corpus: 1.5 s of square-voice bursts.
fn mono_corpus() -> Vec<i32> {
    voices_samples(SEED_MONO, 66_150)
}

/// The offset-match scenario: the query is a 2 s prefix followed by
/// 3 s of indexed content, matched against a two-member index.
struct OffsetCorpus {
    query: Vec<i32>,
    corpus: Vec<Vec<i32>>,
    /// Exact expected modal offset in frames.
    expected_delta_t: f64,
}

fn offset_corpus() -> OffsetCorpus {
    let content = voices_samples(SEED_CONTENT, 132_300);
    let prefix = voices_samples(SEED_PREFIX, 88_200);
    let mut query = prefix;
    query.extend_from_slice(&content);
    let corpus = vec![
        content,
        voices_samples(SEED_OTHER, 132_300),
        voices_samples(SEED_FILLER, 44_100),
    ];
    OffsetCorpus {
        query,
        corpus,
        expected_delta_t: 88_200.0 / 2048.0,
    }
}

/// The stereo mixdown scenario: interleaved stereo content and its
/// explicit channel average — the pipeline's own mix must agree.
fn stereo_corpus() -> (Vec<i32>, Vec<i32>) {
    let stereo = voices_samples_stereo(SEED_STEREO_L, SEED_STEREO_R, 88_200);
    let mono = mono_average(&stereo, 2);
    (stereo, mono)
}

// ------------------------------------------------------------------
// JSON output (hand-rolled: the suite has no third-party crates)
// ------------------------------------------------------------------

/// Serializes one decode vector. `name`/`input` fields differ per kind,
/// so the caller passes them pre-formed.
fn json_decode_vector(name: &str, input_fields: &str, d: &Decoded, with_samples: bool) -> String {
    let mut s = String::new();
    s.push_str("    {\n");
    s.push_str(&format!("      \"name\": \"{name}\",\n"));
    s.push_str(input_fields);
    s.push_str(&format!("      \"sample_rate\": {},\n", d.sample_rate));
    s.push_str(&format!("      \"channels\": {},\n", d.channels));
    s.push_str(&format!(
        "      \"bits_per_sample\": {},\n",
        d.bits_per_sample
    ));
    s.push_str(&format!("      \"frames\": {},\n", d.frames));
    s.push_str(&format!(
        "      \"decoded_samples\": {},\n",
        d.decoded_samples
    ));
    if with_samples {
        let list: Vec<String> = d.samples.iter().map(|v| v.to_string()).collect();
        s.push_str(&format!("      \"samples_i32\": [{}],\n", list.join(", ")));
    }
    s.push_str(&format!(
        "      \"pcm_i32_le_sha256\": \"{}\",\n",
        d.pcm_i32_le_sha256
    ));
    s.push_str(&format!(
        "      \"pcm_i32_le_fnv1a64\": \"{}\"\n",
        d.pcm_i32_le_fnv1a64
    ));
    s.push_str("    }");
    s
}

/// Serializes one signature vector.
fn json_signature_vector(name: &str, input_fields: &str, api: &str, sig: &Signed) -> String {
    let pairs: Vec<String> = sig
        .peaks
        .iter()
        .map(|&(t, f)| format!("[{t}, {f}]"))
        .collect();
    let mut s = String::new();
    s.push_str("    {\n");
    s.push_str(&format!("      \"name\": \"{name}\",\n"));
    s.push_str(input_fields);
    s.push_str(&format!("      \"api\": \"{api}\",\n"));
    s.push_str(&format!("      \"frames\": {},\n", sig.frames));
    s.push_str(&format!("      \"peak_count\": {},\n", sig.peak_count));
    s.push_str(&format!("      \"peaks\": [{}],\n", pairs.join(", ")));
    s.push_str(&format!(
        "      \"fingerprint\": \"{:016x}\",\n",
        sig.fingerprint
    ));
    s.push_str(&format!(
        "      \"peaks_sha256\": \"{}\"\n",
        hex(sha256(&peaks_le(&sig.peaks))
            .expect("sha256 of peaks")
            .as_bytes())
    ));
    s.push_str("    }");
    s
}

/// Serializes the offset-match vector.
fn json_match_vector(name: &str, input_fields: &str, query: &Signed, matches: &[Match]) -> String {
    let entries: Vec<String> = matches
        .iter()
        .map(|m| {
            format!(
                "        {{\n          \"id\": {},\n          \"delta_t\": {},\n          \"votes\": {},\n          \"total_votes\": {}\n        }}",
                m.id, m.delta_t, m.votes, m.total_votes
            )
        })
        .collect();
    let mut s = String::new();
    s.push_str("    {\n");
    s.push_str(&format!("      \"name\": \"{name}\",\n"));
    s.push_str(input_fields);
    s.push_str("      \"api\": \"match_signature\",\n");
    s.push_str(&format!("      \"query_frames\": {},\n", query.frames));
    s.push_str(&format!(
        "      \"query_peak_count\": {},\n",
        query.peak_count
    ));
    s.push_str("      \"matches\": [\n");
    s.push_str(&entries.join(",\n"));
    s.push_str("\n      ]\n");
    s.push_str("    }");
    s
}

/// Input-fields fragment for a fixture-file vector.
fn fixture_input_fields() -> String {
    let bytes = fixture_bytes();
    format!(
        "      \"input_kind\": \"fixture-file\",\n      \"input_path\": \"{FIXTURE_PATH}\",\n      \"input_sha256\": \"{}\",\n",
        hex(sha256(&bytes).expect("sha256 of fixture").as_bytes())
    )
}

/// Input-fields fragment for an inline-hex vector.
fn inline_input_fields(bytes: &[u8]) -> String {
    format!(
        "      \"input_kind\": \"inline-hex\",\n      \"input_hex\": \"{}\",\n",
        hex(bytes)
    )
}

/// Input-fields fragment for a synthetic-voices vector.
fn voices_input_fields(seed: u64, n_samples: usize) -> String {
    format!(
        "      \"input_kind\": \"synthetic-voices\",\n      \"input_params\": {{\"seed\": \"0x{seed:08x}\", \"n_samples\": {n_samples}, \"sample_rate\": 44100, \"voices\": 10}},\n"
    )
}

/// Builds the whole reference.json text.
fn reference_json() -> String {
    let fixture = fixture_bytes();

    // Decode vectors: byte-level container behaviour with the samples
    // pinned inline where the array is small.
    let d8 = measure(&pcm8_offset_wav());
    let d24 = measure(&pcm24_sign_extend_wav());
    let f32w = measure(&float32_clamp_wav());
    let f64w = measure(&float64_thirds_wav());
    let pad = measure(&odd_chunk_pad_wav());
    let partial = measure(&partial_frame_wav());
    let fixture_decoded = measure(&fixture);

    // Signature vectors.
    let mono = mono_corpus();
    let mono_sig = measure_signature(&mono, 1);
    let fixture_sig = measure_signature_of_wav(&fixture);

    // Offset match: the modal delta must sit within ±1 frame of the
    // exact offset, or the corpus drifted and verify fails loudly.
    let oc = offset_corpus();
    let corpus_sigs: Vec<Signature> = oc
        .corpus
        .iter()
        .map(|s| signature(s, 1).expect("corpus pcm accepted"))
        .collect();
    let index = build_index(&corpus_sigs);
    let query_sig = signature(&oc.query, 1).expect("query pcm accepted");
    let matches = match_signature(&query_sig, &index);
    assert!(
        !matches.is_empty() && matches[0].id == 0,
        "offset corpus must match its content member"
    );
    assert!(
        (f64::from(matches[0].delta_t as i32) - oc.expected_delta_t).abs() <= 1.0,
        "modal delta {} drifted from {}",
        matches[0].delta_t,
        oc.expected_delta_t
    );
    let query_signed = signed(&query_sig);

    // Stereo mixdown: the pipeline's mix must equal the explicit average.
    let (stereo, mono_avg) = stereo_corpus();
    let stereo_sig = measure_signature(&stereo, 2);
    let avg_sig = measure_signature(&mono_avg, 1);
    assert_eq!(
        stereo_sig.fingerprint, avg_sig.fingerprint,
        "stereo mixdown drifted from the explicit average"
    );

    let mut s = String::new();
    s.push_str("{\n");
    s.push_str("  \"suite\": \"pith\",\n");
    s.push_str("  \"crate\": \"pith-audio\",\n");
    s.push_str("  \"format_version\": 1,\n");
    s.push_str("  \"generator\": \"cargo run --bin gen-reference -- gen\",\n");
    s.push_str("  \"vectors\": [\n");

    let fixture_fields = fixture_input_fields();
    s.push_str(&json_decode_vector(
        "fixture-tone-wav",
        &fixture_fields,
        &fixture_decoded,
        false,
    ));
    s.push_str(",\n");
    s.push_str(&json_signature_vector(
        "fixture-tone-signature",
        &fixture_fields,
        "signature_of_wav",
        &fixture_sig,
    ));
    s.push_str(",\n");
    s.push_str(&json_decode_vector(
        "pcm8-offset-centred",
        &inline_input_fields(&pcm8_offset_wav()),
        &d8,
        true,
    ));
    s.push_str(",\n");
    s.push_str(&json_decode_vector(
        "pcm24-sign-extension",
        &inline_input_fields(&pcm24_sign_extend_wav()),
        &d24,
        true,
    ));
    s.push_str(",\n");
    s.push_str(&json_decode_vector(
        "float32-clamp-and-nan",
        &inline_input_fields(&float32_clamp_wav()),
        &f32w,
        true,
    ));
    s.push_str(",\n");
    s.push_str(&json_decode_vector(
        "float64-halves-and-thirds",
        &inline_input_fields(&float64_thirds_wav()),
        &f64w,
        true,
    ));
    s.push_str(",\n");
    s.push_str(&json_decode_vector(
        "riff-odd-chunk-pad",
        &inline_input_fields(&odd_chunk_pad_wav()),
        &pad,
        true,
    ));
    s.push_str(",\n");
    s.push_str(&json_decode_vector(
        "partial-frame-dropped",
        &inline_input_fields(&partial_frame_wav()),
        &partial,
        true,
    ));
    s.push_str(",\n");
    s.push_str(&json_signature_vector(
        "voices-signature-mono",
        &voices_input_fields(SEED_MONO, 66_150),
        "signature",
        &mono_sig,
    ));
    s.push_str(",\n");
    s.push_str(&json_match_vector(
        "voices-offset-match",
        &format!(
            "      \"input_kind\": \"synthetic-voices\",\n      \"input_params\": {{\"content_seed\": \"0x{SEED_CONTENT:08x}\", \"content_samples\": 132300, \"prefix_seed\": \"0x{SEED_PREFIX:08x}\", \"prefix_samples\": 88200, \"other_seed\": \"0x{SEED_OTHER:08x}\", \"filler_seed\": \"0x{SEED_FILLER:08x}\", \"index\": [0, 1, 2]}},\n"
        ),
        &query_signed,
        &matches,
    ));
    s.push_str(",\n");
    s.push_str(&json_signature_vector(
        "voices-stereo-mixdown",
        &format!(
            "      \"input_kind\": \"synthetic-voices\",\n      \"input_params\": {{\"left_seed\": \"0x{SEED_STEREO_L:08x}\", \"right_seed\": \"0x{SEED_STEREO_R:08x}\", \"n_samples\": 88200, \"channels\": 2}},\n      \"mixdown_of\": \"stereo\",\n"
        ),
        "signature",
        &stereo_sig,
    ));
    s.push_str(",\n");
    s.push_str(&json_signature_vector(
        "voices-stereo-mono-average",
        &format!(
            "      \"input_kind\": \"synthetic-voices\",\n      \"input_params\": {{\"left_seed\": \"0x{SEED_STEREO_L:08x}\", \"right_seed\": \"0x{SEED_STEREO_R:08x}\", \"n_samples\": 88200, \"channels\": 2}},\n      \"mixdown_of\": \"mono-average\",\n"
        ),
        "signature",
        &avg_sig,
    ));
    s.push_str("\n  ],\n");

    // Error behaviour is part of the cross-SDK contract: the kind name
    // is stable, the message text is not depended on. The kinds below
    // are computed here so a decoder change that shifts a kind fails
    // loudly instead of silently drifting the file.
    let short_header = wav::decode(b"RIFF").expect_err("4-byte input must be truncated");
    let not_a_wav =
        wav::decode(b"not a wave file at all.........").expect_err("bad magic must error");
    let avi_form = {
        let mut f = pcm_wav(1, 1, 8_000, 8, &[0x80]);
        f[8..12].copy_from_slice(b"AVI ");
        wav::decode(&f).expect_err("non-WAVE form must error")
    };
    let adpcm = pcm_wav(2, 1, 8_000, 4, &[0u8; 8]);
    let adpcm_err = wav::decode(&adpcm).expect_err("ADPCM must be unsupported");
    let depth12 = pcm_wav(1, 1, 8_000, 12, &[0u8; 8]);
    let depth12_err = wav::decode(&depth12).expect_err("12-bit PCM must be unsupported");
    let only_fmt = wav_file(&[chunk(b"fmt ", &fmt_chunk(1, 1, 8_000, 8))]);
    let only_fmt_err = wav::decode(&only_fmt).expect_err("missing data must error");
    let zero_rate = pcm_wav(1, 1, 0, 16, &[0x00, 0x00]);
    let zero_rate_err = wav::decode(&zero_rate).expect_err("zero rate must error");
    let bad_align = {
        let mut fmt = fmt_chunk(1, 1, 8_000, 8);
        fmt[12] = 7;
        let f = wav_file(&[chunk(b"fmt ", &fmt), chunk(b"data", &[0x80])]);
        wav::decode(&f).expect_err("block_align mismatch must error")
    };
    let truncated = {
        let mut f = pcm_wav(1, 1, 8_000, 16, &[1, 0, 2, 0, 3, 0, 4, 0]);
        f.truncate(f.len() - 3);
        wav::decode(&f).expect_err("short payload must error")
    };
    let lo_rate = {
        let mono = voices_samples(SEED_MONO, 22_050);
        let f = pcm_wav(1, 1, 22_050, 16, &pcm16_data(&mono));
        signature_of_wav(&f).expect_err("22 050 Hz must be refused")
    };
    let garbage = signature_of_wav(b"not a wav").expect_err("garbage must be Decode");

    let errors: [(&str, &str, String, &str, &str); 11] = [
        (
            "short-riff-header",
            "wav.decode",
            hex(b"RIFF"),
            error_kind(&short_header),
            "truncated",
        ),
        (
            "not-a-wav",
            "wav.decode",
            hex(b"not a wave file at all........."),
            error_kind(&not_a_wav),
            "invalid-magic",
        ),
        (
            "riff-avi-form",
            "wav.decode",
            {
                let mut f = pcm_wav(1, 1, 8_000, 8, &[0x80]);
                f[8..12].copy_from_slice(b"AVI ");
                hex(&f)
            },
            error_kind(&avi_form),
            "invalid-magic",
        ),
        (
            "adpcm-format-tag",
            "wav.decode",
            hex(&adpcm),
            error_kind(&adpcm_err),
            "unsupported",
        ),
        (
            "pcm-12-bit-depth",
            "wav.decode",
            hex(&depth12),
            error_kind(&depth12_err),
            "unsupported",
        ),
        (
            "missing-data-chunk",
            "wav.decode",
            hex(&only_fmt),
            error_kind(&only_fmt_err),
            "bad-value",
        ),
        (
            "zero-sample-rate",
            "wav.decode",
            hex(&zero_rate),
            error_kind(&zero_rate_err),
            "bad-value",
        ),
        (
            "block-align-mismatch",
            "wav.decode",
            {
                let mut fmt = fmt_chunk(1, 1, 8_000, 8);
                fmt[12] = 7;
                hex(&wav_file(&[chunk(b"fmt ", &fmt), chunk(b"data", &[0x80])]))
            },
            error_kind(&bad_align),
            "bad-value",
        ),
        (
            "truncated-chunk-payload",
            "wav.decode",
            {
                let mut f = pcm_wav(1, 1, 8_000, 16, &[1, 0, 2, 0, 3, 0, 4, 0]);
                f.truncate(f.len() - 3);
                hex(&f)
            },
            error_kind(&truncated),
            "truncated",
        ),
        (
            "wrong-sample-rate-facade",
            "signature_of_wav",
            {
                let mono = voices_samples(SEED_MONO, 22_050);
                hex(&pcm_wav(1, 1, 22_050, 16, &pcm16_data(&mono)))
            },
            facade_error_kind(&lo_rate),
            "unsupported",
        ),
        (
            "garbage-input-facade",
            "signature_of_wav",
            hex(b"not a wav"),
            facade_error_kind(&garbage),
            "decode",
        ),
    ];
    let garbage_kind = facade_error_kind(&garbage);
    assert_eq!(
        garbage_kind, "decode",
        "garbage must map to the decode kind"
    );

    s.push_str("  \"error_vectors\": [\n");
    for (i, (name, api, input_hex, kind, expected)) in errors.iter().enumerate() {
        assert_eq!(kind, expected, "error kind for {name} drifted");
        s.push_str("    {\n");
        s.push_str(&format!("      \"name\": \"{name}\",\n"));
        s.push_str(&format!("      \"api\": \"{api}\",\n"));
        s.push_str("      \"input_kind\": \"inline-hex\",\n");
        s.push_str(&format!("      \"input_hex\": \"{input_hex}\",\n"));
        s.push_str(&format!("      \"error\": \"{kind}\"\n"));
        s.push_str(if i + 1 == errors.len() {
            "    }\n"
        } else {
            "    },\n"
        });
    }
    s.push_str("  ]\n");
    s.push_str("}\n");
    s
}

fn repo_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

fn fixture_bytes() -> Vec<u8> {
    fs::read(repo_root().join(FIXTURE_PATH))
        .unwrap_or_else(|e| panic!("cannot read {FIXTURE_PATH}: {e}"))
}

fn main() -> ExitCode {
    run(std::env::args().nth(1).unwrap_or_default().as_str())
}

/// One CLI invocation, split out of [`main`] so the mode dispatch is
/// unit-testable.
fn run(mode: &str) -> ExitCode {
    match mode {
        "gen" => {
            let json = reference_json();
            let path = repo_root().join(REFERENCE_PATH);
            fs::write(&path, &json).unwrap_or_else(|e| panic!("cannot write {path:?}: {e}"));
            println!("wrote {} ({} bytes)", path.display(), json.len());
            ExitCode::SUCCESS
        }
        "verify" => {
            let json = reference_json();
            let path = repo_root().join(REFERENCE_PATH);
            let committed = match fs::read(&path) {
                Ok(b) => b,
                Err(e) => {
                    eprintln!("FAIL: cannot read {path:?}: {e}");
                    return ExitCode::FAILURE;
                }
            };
            if committed == json.as_bytes() {
                println!("reference.json is current");
                ExitCode::SUCCESS
            } else {
                let off = committed
                    .iter()
                    .zip(json.as_bytes())
                    .position(|(a, b)| a != b)
                    .unwrap_or(committed.len().min(json.len()));
                eprintln!(
                    "FAIL: reference.json is stale: committed {} bytes, computed {} bytes, first difference at byte {off}",
                    committed.len(),
                    json.len()
                );
                ExitCode::FAILURE
            }
        }
        _ => {
            eprintln!("usage: gen-reference <gen|verify> (got {mode:?})");
            ExitCode::from(2)
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use pith_audio::reference::SplitMix64;

    /// The fixture's ground-truth values, pinned here so a port
    /// regression cannot quietly rewrite them.
    const FIXTURE_SHA256: &str = "056d902b650aad29ed5c1a29417c467f5cd4e4615a15e054f17a6e8824bb38fd";
    const FIXTURE_PCM_SHA256: &str =
        "813970b3798192fd2db23c34b10658c94183096f671a790e40fd26edc6639e0d";
    const FIXTURE_PEAKS_SHA256: &str =
        "8c6ac0719bb7caed61e66f978da85ab5b66639aa279457d8f88731be2dea1ec8";
    const FIXTURE_PEAK_COUNT: usize = 42;
    const FIXTURE_FRAMES: u32 = 20;

    #[test]
    fn fixture_measures_reference_values() {
        let bytes = fixture_bytes();
        let d = measure(&bytes);
        assert_eq!(d.sample_rate, 44_100);
        assert_eq!(d.channels, 1);
        assert_eq!(d.bits_per_sample, 16);
        assert_eq!(d.decoded_samples, 44_100);
        assert_eq!(d.frames, 44_100);
        assert_eq!(
            hex(sha256(&bytes).expect("sha256").as_bytes()),
            FIXTURE_SHA256
        );
        assert_eq!(d.pcm_i32_le_sha256, FIXTURE_PCM_SHA256);

        let sig = measure_signature_of_wav(&bytes);
        assert_eq!(sig.frames, FIXTURE_FRAMES);
        assert_eq!(sig.peak_count, FIXTURE_PEAK_COUNT);
        assert_eq!(
            hex(sha256(&peaks_le(&sig.peaks)).expect("sha256").as_bytes()),
            FIXTURE_PEAKS_SHA256
        );
        assert!(!sig.peaks.is_empty(), "fixture must produce peaks");
    }

    #[test]
    fn json_carries_fixture_identity_and_kinds() {
        let json = reference_json();
        assert!(json.contains("\"suite\": \"pith\""));
        assert!(json.contains(FIXTURE_SHA256));
        assert!(json.contains(FIXTURE_PCM_SHA256));
        // Every error kind the generator computes is one the mapping
        // knows; the inputs cover invalid-magic, unsupported, bad-value
        // and truncated, plus the facade's decode kind.
        assert!(json.contains("\"error\": \"invalid-magic\""));
        assert!(json.contains("\"error\": \"unsupported\""));
        assert!(json.contains("\"error\": \"bad-value\""));
        assert!(json.contains("\"error\": \"truncated\""));
        assert!(json.contains("\"error\": \"decode\""));
    }

    #[test]
    fn decode_vectors_pin_their_documented_values() {
        let d = measure(&pcm8_offset_wav());
        assert_eq!(d.samples, vec![-128, 0, 127, -127]);
        let d = measure(&pcm24_sign_extend_wav());
        assert_eq!(d.samples, vec![-8_388_608, 8_388_607, 0, -1, 256]);
        let d = measure(&float32_clamp_wav());
        assert_eq!(
            d.samples,
            vec![0, i32::MIN, i32::MAX, 1_073_741_824, i32::MAX, 0]
        );
        let d = measure(&float64_thirds_wav());
        assert_eq!(d.samples, vec![536_870_912, -1_073_741_824, 715_827_883]);
        let d = measure(&odd_chunk_pad_wav());
        assert_eq!(d.samples, vec![1, -2]);
        let d = measure(&partial_frame_wav());
        assert_eq!(d.samples, vec![5]);
        assert_eq!(d.frames, 1);
    }

    #[test]
    fn offset_match_pins_member_zero_near_expected_delta() {
        let oc = offset_corpus();
        let corpus_sigs: Vec<Signature> = oc
            .corpus
            .iter()
            .map(|s| signature(s, 1).expect("corpus pcm accepted"))
            .collect();
        let index = build_index(&corpus_sigs);
        let m = match_signature(&signature(&oc.query, 1).expect("query"), &index);
        assert!(!m.is_empty());
        assert_eq!(m[0].id, 0);
        assert!((f64::from(m[0].delta_t as i32) - oc.expected_delta_t).abs() <= 1.0);
        assert!(m[0].votes >= 8, "expected a decisive vote mass");
    }

    #[test]
    fn hex_encodes_lowercase_bytes() {
        assert_eq!(hex(&[0x00, 0x0f, 0xf0, 0xff]), "000ff0ff");
    }

    #[test]
    fn peaks_le_serializes_t_then_f() {
        assert_eq!(
            peaks_le(&[(1, 2), (3, 4)]),
            [1, 0, 0, 0, 2, 0, 3, 0, 0, 0, 4, 0]
        );
    }

    #[test]
    fn error_kinds_map_one_to_one() {
        assert_eq!(
            error_kind(&pith_digest::Error::InvalidMagic { what: "x" }),
            "invalid-magic"
        );
        assert_eq!(
            error_kind(&pith_digest::Error::Truncated {
                what: "x",
                needed: 1,
                found: 0
            }),
            "truncated"
        );
        assert_eq!(error_kind(&pith_digest::Error::BadValue("x")), "bad-value");
        assert_eq!(
            error_kind(&pith_digest::Error::Unsupported("x")),
            "unsupported"
        );
        assert_eq!(
            error_kind(&pith_digest::Error::TooLarge {
                what: "x",
                limit: 1
            }),
            "too-large"
        );
        assert_eq!(
            facade_error_kind(&pith_audio::Error::BadValue("x")),
            "bad-value"
        );
        assert_eq!(
            facade_error_kind(&pith_audio::Error::Unsupported("x")),
            "unsupported"
        );
        assert_eq!(
            facade_error_kind(&pith_audio::Error::Decode("x".into())),
            "decode"
        );
    }

    #[test]
    fn splitmix64_stream_is_pinned() {
        let mut rng = SplitMix64::new(0);
        assert_eq!(rng.next_u64(), 0xe220_a839_7b1d_cdaf);
        assert_eq!(rng.next_u64(), 0x6e78_9e6a_a1b9_65f4);
    }

    #[test]
    fn gen_rewrites_the_committed_file() {
        assert_eq!(run("gen"), ExitCode::SUCCESS);
        // Determinism: the regenerated copy must equal what gen produced
        // a moment before, so verify mode stays green.
        assert_eq!(run("verify"), ExitCode::SUCCESS);
    }

    #[test]
    fn unknown_mode_exits_two() {
        assert_eq!(run("bogus"), ExitCode::from(2));
        assert_eq!(run(""), ExitCode::from(2));
    }
}
